// flow-typed signature: 4bc35d06255713c8c2fd8cd8bca1627b
// flow-typed version: <<STUB>>/eslint-plugin-env_v^0.0.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-env/lib/rules/no-undef-env' {
  declare module.exports: any;
}

declare module 'eslint-plugin-env/test/lib/rules/no-undef-env' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-env/index' {
  declare module.exports: $Exports<'eslint-plugin-env'>;
}
declare module 'eslint-plugin-env/index.js' {
  declare module.exports: $Exports<'eslint-plugin-env'>;
}
declare module 'eslint-plugin-env/lib/rules/no-undef-env.js' {
  declare module.exports: $Exports<'eslint-plugin-env/lib/rules/no-undef-env'>;
}
declare module 'eslint-plugin-env/test/lib/rules/no-undef-env.js' {
  declare module.exports: $Exports<'eslint-plugin-env/test/lib/rules/no-undef-env'>;
}
